name: Build and push a Docker image directly on the server
on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    name: Build and push a Docker image directly on the server
    runs-on: ubuntu-latest
    steps:
      - name: Build and push a Docker image
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && sbt docker:publish
      - name: Stop the bot
        run: dcstop --timeout 30 karpovka-smoke-break-bot
      - name: Start the bot with the new image
        run: dcup -d karpovka-smoke-break-bot
      - name: Cleanup unnecessary Docker images
        run: docker images | grep none | awk '{print $3}' | xargs -I _ docker rmi -f _ 
